#define	STRANGE_OBJECT	0
#define	AMULET_OF_YENDOR	1
#define	FOOD_RATION	2
#define	TRIPE_RATION	3
#define	PANCAKE	4
#define	DEAD_LIZARD	5
#define	FORTUNE_COOKIE	6
#define	CARROT	7
#define	TIN	8
#define	ORANGE	9
#define	APPLE	10
#define	PEAR	11
#define	MELON	12
#define	BANANA	13
#define	CANDY_BAR	14
#define	EGG	15
#define	CLOVE_OF_GARLIC	16
#define	DEAD_HUMAN	17
#define	DEAD_GIANT_ANT	18
#define	DEAD_GIANT_BAT	19
#define	DEAD_CENTAUR	20
#define	DEAD_DRAGON	21
#define	DEAD_FLOATING_EYE	22
#define	DEAD_FREEZING_SPHERE	23
#define	DEAD_GNOME	24
#define	DEAD_HOBGOBLIN	25
#define	DEAD_STALKER	26
#define	DEAD_JACKAL	27
#define	DEAD_KOBOLD	28
#define	DEAD_LEPRECHAUN	29
#define	DEAD_MIMIC	30
#define	DEAD_NYMPH	31
#define	DEAD_ORC	32
#define	DEAD_PURPLE_WORM	33
#define	DEAD_QUASIT	34
#define	DEAD_RUST_MONSTER	35
#define	DEAD_SNAKE	36
#define	DEAD_TROLL	37
#define	DEAD_UMBER_HULK	38
#define	DEAD_VAMPIRE	39
#define	DEAD_WRAITH	40
#define	DEAD_XORN	41
#define	DEAD_YETI	42
#define	DEAD_ZOMBIE	43
#define	DEAD_ACID_BLOB	44
#define	DEAD_GIANT_BEETLE	45
#define	DEAD_COCKATRICE	46
#define	DEAD_DOG	47
#define	DEAD_ETTIN	48
#define	DEAD_FOG_CLOUD	49
#define	DEAD_GELATINOUS_CUBE	50
#define	DEAD_HOMUNCULUS	51
#define	DEAD_IMP	52
#define	DEAD_JAGUAR	53
#define	DEAD_KILLER_BEE	54
#define	DEAD_LEOCROTTA	55
#define	DEAD_MINOTAUR	56
#define	DEAD_NURSE	57
#define	DEAD_OWLBEAR	58
#define	DEAD_PIERCER	59
#define	DEAD_QUIVERING_BLOB	60
#define	DEAD_GIANT_RAT	61
#define	DEAD_GIANT_SCORPION	62
#define	DEAD_TENGU	63
#define	DEAD_UNICORN	64
#define	DEAD_VIOLET_FUNGI	65
#define	DEAD_LONG_WORM	66
#define	DEAD_XAN	67
#define	DEAD_YELLOW_LIGHT	68
#define	DEAD_ZRUTY	69
#define	ARROW	70
#define	SLING_BULLET	71
#define	CROSSBOW_BOLT	72
#define	DART	73
#define	ROCK	74
#define	BOOMERANG	75
#define	MACE	76
#define	AXE	77
#define	FLAIL	78
#define	LONG_SWORD	79
#define	TWO_HANDED_SWORD	80
#define	DAGGER	81
#define	WORM_TOOTH	82
#define	CRYSKNIFE	83
#define	SPEAR	84
#define	BOW	85
#define	SLING	86
#define	CROSSBOW	87
#define	WHISTLE	88
#define	MAGIC_WHISTLE	89
#define	EXPENSIVE_CAMERA	90
#define	ICE_BOX	91
#define	HEAVY_IRON_BALL	92
#define	IRON_CHAIN	93
#define	ENORMOUS_ROCK	94
#define	HELMET	95
#define	PLATE_MAIL	96
#define	SPLINT_MAIL	97
#define	BANDED_MAIL	98
#define	CHAIN_MAIL	99
#define	SCALE_MAIL	100
#define	RING_MAIL	101
#define	STUDDED_LEATHER_ARMOR	102
#define	LEATHER_ARMOR	103
#define	ELVEN_CLOAK	104
#define	SHIELD	105
#define	PAIR_OF_GLOVES	106
#define	POT_RESTORE_STRENGTH	107
#define	POT_BOOZE	108
#define	POT_INVISIBILITY	109
#define	POT_FRUIT_JUICE	110
#define	POT_HEALING	111
#define	POT_PARALYSIS	112
#define	POT_MONSTER_DETECTION	113
#define	POT_OBJECT_DETECTION	114
#define	POT_SICKNESS	115
#define	POT_CONFUSION	116
#define	POT_GAIN_STRENGTH	117
#define	POT_SPEED	118
#define	POT_BLINDNESS	119
#define	POT_GAIN_LEVEL	120
#define	POT_EXTRA_HEALING	121
#define	POT_LEVITATION	122
#define	SCR_ENCHANT_ARMOR	127
#define	SCR_DESTROY_ARMOR	128
#define	SCR_CONFUSE_MONSTER	129
#define	SCR_SCARE_MONSTER	130
#define	SCR_BLANK_PAPER	131
#define	SCR_REMOVE_CURSE	132
#define	SCR_ENCHANT_WEAPON	133
#define	SCR_DAMAGE_WEAPON	134
#define	SCR_CREATE_MONSTER	135
#define	SCR_TAMING	136
#define	SCR_GENOCIDE	137
#define	SCR_LIGHT	138
#define	SCR_TELEPORTATION	139
#define	SCR_GOLD_DETECTION	140
#define	SCR_FOOD_DETECTION	141
#define	SCR_IDENTIFY	142
#define	SCR_MAGIC_MAPPING	143
#define	SCR_AMNESIA	144
#define	SCR_FIRE	145
#define	SCR_PUNISHMENT	146
#define	WAN_LIGHT	151
#define	WAN_SECRET_DOOR_DETECTION	152
#define	WAN_CREATE_MONSTER	153
#define	WAN_WISHING	154
#define	WAN_STRIKING	155
#define	WAN_SLOW_MONSTER	156
#define	WAN_SPEED_MONSTER	157
#define	WAN_UNDEAD_TURNING	158
#define	WAN_POLYMORPH	159
#define	WAN_CANCELLATION	160
#define	WAN_TELEPORT_MONSTER	161
#define	WAN_MAKE_INVISIBLE	162
#define	WAN_DIGGING	163
#define	WAN_MAGIC_MISSILE	164
#define	WAN_FIRE	165
#define	WAN_SLEEP	166
#define	WAN_COLD	167
#define	WAN_DEATH	168
#define	Adornment	u.uprops[0].p_flgs
#define	RIN_ADORNMENT	172
#define	Teleportation	u.uprops[1].p_flgs
#define	RIN_TELEPORTATION	173
#define	Regeneration	u.uprops[2].p_flgs
#define	RIN_REGENERATION	174
#define	Searching	u.uprops[3].p_flgs
#define	RIN_SEARCHING	175
#define	See_invisible	u.uprops[4].p_flgs
#define	RIN_SEE_INVISIBLE	176
#define	Stealth	u.uprops[5].p_flgs
#define	RIN_STEALTH	177
#define	Levitation	u.uprops[6].p_flgs
#define	RIN_LEVITATION	178
#define	Poison_resistance	u.uprops[7].p_flgs
#define	RIN_POISON_RESISTANCE	179
#define	Aggravate_monster	u.uprops[8].p_flgs
#define	RIN_AGGRAVATE_MONSTER	180
#define	Hunger	u.uprops[9].p_flgs
#define	RIN_HUNGER	181
#define	Fire_resistance	u.uprops[10].p_flgs
#define	RIN_FIRE_RESISTANCE	182
#define	Cold_resistance	u.uprops[11].p_flgs
#define	RIN_COLD_RESISTANCE	183
#define	Protection_from_shape_changers	u.uprops[12].p_flgs
#define	RIN_PROTECTION_FROM_SHAPE_CHANGERS	184
#define	Conflict	u.uprops[13].p_flgs
#define	RIN_CONFLICT	185
#define	Gain_strength	u.uprops[14].p_flgs
#define	RIN_GAIN_STRENGTH	186
#define	Increase_damage	u.uprops[15].p_flgs
#define	RIN_INCREASE_DAMAGE	187
#define	Protection	u.uprops[16].p_flgs
#define	RIN_PROTECTION	188
#define	Warning	u.uprops[17].p_flgs
#define	RIN_WARNING	189
#define	Teleport_control	u.uprops[18].p_flgs
#define	RIN_TELEPORT_CONTROL	190
#define	DIAMOND	193
#define	RUBY	194
#define	SAPPHIRE	195
#define	EMERALD	196
#define	TURQUOISE	197
#define	AQUAMARINE	198
#define	TOURMALINE	199
#define	TOPAZ	200
#define	OPAL	201
#define	GARNET	202
#define	AMETHYST	203
#define	AGATE	204
#define	ONYX	205
#define	JASPER	206
#define	JADE	207
/* #define WORTHLESS_PIECE_OF_BLUE_GLASS	208 */
/* #define WORTHLESS_PIECE_OF_RED_GLASS	209 */
/* #define WORTHLESS_PIECE_OF_YELLOW_GLASS	210 */
/* #define WORTHLESS_PIECE_OF_GREEN_GLASS	211 */

#define	CORPSE	DEAD_HUMAN
#define	LAST_GEM	(JADE+1)
#define	LAST_RING	19
#define	NROFOBJECTS	211
