#define	STRANGE_OBJECT	0
#define	AMULET_OF_YENDOR	1
#define	FOOD_RATION	2
#define	TRIPE_RATION	3
#define	PANCAKE	4
#define	DEAD_LIZARD	5
#define	FORTUNE_COOKIE	6
#define	CARROT	7
#define	SLICE_OF_PIZZA	8
#define	CREAM_PIE	9
#define	TIN	10
#define	ORANGE	11
#define	APPLE	12
#define	PEAR	13
#define	MELON	14
#define	BANANA	15
#define	CANDY_BAR	16
#define	EGG	17
#define	CLOVE_OF_GARLIC	18
#define	LUMP_OF_ROYAL_JELLY	19
#define	DEAD_HUMAN	20
#define	DEAD_GIANT_ANT	21
#define	DEAD_GIANT_BAT	22
#define	DEAD_CENTAUR	23
#define	DEAD_DRAGON	24
#define	DEAD_FLOATING_EYE	25
#define	DEAD_FREEZING_SPHERE	26
#define	DEAD_GNOME	27
#define	DEAD_HOBGOBLIN	28
#define	DEAD_STALKER	29
#define	DEAD_JACKAL	30
#define	DEAD_KOBOLD	31
#define	DEAD_LEPRECHAUN	32
#define	DEAD_MIMIC	33
#define	DEAD_NYMPH	34
#define	DEAD_ORC	35
#define	DEAD_PURPLE_WORM	36
#define	DEAD_QUANTUM_MECHANIC	37
#define	DEAD_RUST_MONSTER	38
#define	DEAD_SNAKE	39
#define	DEAD_TROLL	40
#define	DEAD_UMBER_HULK	41
#define	DEAD_VAMPIRE	42
#define	DEAD_WRAITH	43
#define	DEAD_XORN	44
#define	DEAD_YETI	45
#define	DEAD_ZOMBIE	46
#define	DEAD_ACID_BLOB	47
#define	DEAD_GIANT_BEETLE	48
#define	DEAD_COCKATRICE	49
#define	DEAD_DOG	50
#define	DEAD_ETTIN	51
#define	DEAD_FOG_CLOUD	52
#define	DEAD_GELATINOUS_CUBE	53
#define	DEAD_HOMUNCULUS	54
#define	DEAD_IMP	55
#define	DEAD_JAGUAR	56
#define	DEAD_KILLER_BEE	57
#define	DEAD_LEOCROTTA	58
#define	DEAD_MINOTAUR	59
#define	DEAD_NURSE	60
#define	DEAD_OWLBEAR	61
#define	DEAD_PIERCER	62
#define	DEAD_QUIVERING_BLOB	63
#define	DEAD_GIANT_RAT	64
#define	DEAD_GIANT_SCORPION	65
#define	DEAD_TENGU	66
#define	DEAD_UNICORN	67
#define	DEAD_VIOLET_FUNGUS	68
#define	DEAD_LONG_WORM	69
#define	DEAD_XAN	70
#define	DEAD_YELLOW_LIGHT	71
#define	DEAD_ZRUTY	72
#define	DEAD_SOLDIER	73
#define	DEAD_GIANT	74
#define	DEAD_DEMON	75
#define	ARROW	76
#define	SLING_BULLET	77
#define	CROSSBOW_BOLT	78
#define	DART	79
#define	SHURIKEN	80
#define	ROCK	81
#define	BOOMERANG	82
#define	MACE	83
#define	AXE	84
#define	FLAIL	85
#define	LONG_SWORD	86
#define	TWO_HANDED_SWORD	87
#define	DAGGER	88
#define	WORM_TOOTH	89
#define	CRYSKNIFE	90
#define	AKLYS	91
#define	BARDICHE	92
#define	BEC_DE_CORBIN	93
#define	BILL_GUISARME	94
#define	CLUB	95
#define	FAUCHARD	96
#define	GLAIVE	97
#define	GUISARME	98
#define	HALBERD	99
#define	LUCERN_HAMMER	100
#define	JAVELIN	101
#define	KATANA	102
#define	LANCE	103
#define	MORNING_STAR	104
#define	PARTISAN	105
#define	RANSEUR	106
#define	SCIMITAR	107
#define	SPETUM	108
#define	BROAD_SWORD	109
#define	SHORT_SWORD	110
#define	TRIDENT	111
#define	VOULGE	112
#define	SPEAR	113
#define	BOW	114
#define	SLING	115
#define	CROSSBOW	116
#define	WHISTLE	117
#define	LEASH	118
#define	MAGIC_WHISTLE	119
#define	BLINDFOLD	120
#define	MIRROR	121
#define	EXPENSIVE_CAMERA	122
#define	ICE_BOX	123
#define	PICK_AXE	124
#define	MAGIC_MARKER	125
#define	STETHOSCOPE	126
#define	CAN_OPENER	127
#define	HEAVY_IRON_BALL	128
#define	IRON_CHAIN	129
#define	ENORMOUS_ROCK	130
#define	HELMET	131
#define	PLATE_MAIL	132
#define	SPLINT_MAIL	133
#define	BANDED_MAIL	134
#define	CHAIN_MAIL	135
#define	SCALE_MAIL	136
#define	RING_MAIL	137
#define	STUDDED_LEATHER_ARMOR	138
#define	ELFIN_CHAIN_MAIL	139
#define	BRONZE_PLATE_MAIL	140
#define	CRYSTAL_PLATE_MAIL	141
#define	LEATHER_ARMOR	142
#define	ELVEN_CLOAK	143
#define	SHIELD	144
#define	PAIR_OF_GLOVES	145
#define	POT_RESTORE_STRENGTH	146
#define	POT_GAIN_ENERGY	147
#define	POT_BOOZE	148
#define	POT_INVISIBILITY	149
#define	POT_FRUIT_JUICE	150
#define	POT_HEALING	151
#define	POT_PARALYSIS	152
#define	POT_MONSTER_DETECTION	153
#define	POT_OBJECT_DETECTION	154
#define	POT_SICKNESS	155
#define	POT_CONFUSION	156
#define	POT_GAIN_STRENGTH	157
#define	POT_SPEED	158
#define	POT_BLINDNESS	159
#define	POT_GAIN_LEVEL	160
#define	POT_EXTRA_HEALING	161
#define	POT_LEVITATION	162
#define	POT_HALLUCINATION	163
#define	POT_HOLY_WATER	164
#define	SCR_MAIL	167
#define	SCR_ENCHANT_ARMOR	168
#define	SCR_DESTROY_ARMOR	169
#define	SCR_CONFUSE_MONSTER	170
#define	SCR_SCARE_MONSTER	171
#define	SCR_BLANK_PAPER	172
#define	SCR_REMOVE_CURSE	173
#define	SCR_ENCHANT_WEAPON	174
#define	SCR_DAMAGE_WEAPON	175
#define	SCR_CREATE_MONSTER	176
#define	SCR_TAMING	177
#define	SCR_GENOCIDE	178
#define	SCR_LIGHT	179
#define	SCR_TELEPORTATION	180
#define	SCR_GOLD_DETECTION	181
#define	SCR_FOOD_DETECTION	182
#define	SCR_IDENTIFY	183
#define	SCR_MAGIC_MAPPING	184
#define	SCR_AMNESIA	185
#define	SCR_FIRE	186
#define	SCR_PUNISHMENT	187
#define	WAN_LIGHT	192
#define	WAN_SECRET_DOOR_DETECTION	193
#define	WAN_CREATE_MONSTER	194
#define	WAN_WISHING	195
#define	WAN_STRIKING	196
#define	WAN_NOTHING	197
#define	WAN_SLOW_MONSTER	198
#define	WAN_SPEED_MONSTER	199
#define	WAN_UNDEAD_TURNING	200
#define	WAN_POLYMORPH	201
#define	WAN_CANCELLATION	202
#define	WAN_TELEPORTATION	203
#define	WAN_MAKE_INVISIBLE	204
#define	WAN_PROBING	205
#define	WAN_DIGGING	206
#define	WAN_MAGIC_MISSILE	207
#define	WAN_FIRE	208
#define	WAN_SLEEP	209
#define	WAN_COLD	210
#define	WAN_DEATH	211
#define	SPE_MAGIC_MISSILE	214
#define	SPE_FIREBALL	215
#define	SPE_SLEEP	216
#define	SPE_CONE_OF_COLD	217
#define	SPE_FINGER_OF_DEATH	218
#define	SPE_HEALING	219
#define	SPE_DETECT_MONSTERS	220
#define	SPE_FORCE_BOLT	221
#define	SPE_LIGHT	222
#define	SPE_CONFUSE_MONSTER	223
#define	SPE_CURE_BLINDNESS	224
#define	SPE_SLOW_MONSTER	225
#define	SPE_CREATE_MONSTER	226
#define	SPE_DETECT_FOOD	227
#define	SPE_HASTE_SELF	228
#define	SPE_CAUSE_FEAR	229
#define	SPE_CURE_SICKNESS	230
#define	SPE_DETECT_UNSEEN	231
#define	SPE_EXTRA_HEALING	232
#define	SPE_CHARM_MONSTER	233
#define	SPE_LEVITATION	234
#define	SPE_RESTORE_STRENGTH	235
#define	SPE_INVISIBILITY	236
#define	SPE_DETECT_TREASURE	237
#define	SPE_DIG	238
#define	SPE_REMOVE_CURSE	239
#define	SPE_MAGIC_MAPPING	240
#define	SPE_IDENTIFY	241
#define	SPE_TURN_UNDEAD	242
#define	SPE_POLYMORPH	243
#define	SPE_CREATE_FAMILIAR	244
#define	SPE_TELEPORT_AWAY	245
#define	SPE_CANCELLATION	246
#define	SPE_GENOCIDE	247
#define	Adornment	u.uprops[0].p_flgs
#define	RIN_ADORNMENT	252
#define	HTeleportation	u.uprops[1].p_flgs
#define	Teleportation	((HTeleportation) || index("LNt", u.usym))
#define	RIN_TELEPORTATION	253
#define	HRegeneration	u.uprops[2].p_flgs
#define	Regeneration	((HRegeneration) || index("TVi", u.usym))
#define	RIN_REGENERATION	254
#define	Searching	u.uprops[3].p_flgs
#define	RIN_SEARCHING	255
#define	HSee_invisible	u.uprops[4].p_flgs
#define	See_invisible	((HSee_invisible) || index("I", u.usym))
#define	RIN_SEE_INVISIBLE	256
#define	Stealth	u.uprops[5].p_flgs
#define	RIN_STEALTH	257
#define	Levitation	u.uprops[6].p_flgs
#define	RIN_LEVITATION	258
#define	HPoison_resistance	u.uprops[7].p_flgs
#define	Poison_resistance	((HPoison_resistance) || index("abcghikqsuvxyADFQSVWXZ&", u.usym))
#define	RIN_POISON_RESISTANCE	259
#define	Aggravate_monster	u.uprops[8].p_flgs
#define	RIN_AGGRAVATE_MONSTER	260
#define	Hunger	u.uprops[9].p_flgs
#define	RIN_HUNGER	261
#define	HFire_resistance	u.uprops[10].p_flgs
#define	Fire_resistance	((HFire_resistance) || index("gD&", u.usym))
#define	RIN_FIRE_RESISTANCE	262
#define	HCold_resistance	u.uprops[11].p_flgs
#define	Cold_resistance	((HCold_resistance) || index("gFY", u.usym))
#define	RIN_COLD_RESISTANCE	263
#define	Protection_from_shape_changers	u.uprops[12].p_flgs
#define	RIN_PROTECTION_FROM_SHAPE_CHAN	264
#define	Conflict	u.uprops[13].p_flgs
#define	RIN_CONFLICT	265
#define	Gain_strength	u.uprops[14].p_flgs
#define	RIN_GAIN_STRENGTH	266
#define	Increase_damage	u.uprops[15].p_flgs
#define	RIN_INCREASE_DAMAGE	267
#define	Protection	u.uprops[16].p_flgs
#define	RIN_PROTECTION	268
#define	Warning	u.uprops[17].p_flgs
#define	RIN_WARNING	269
#define	HTeleport_control	u.uprops[18].p_flgs
#define	Teleport_control	((HTeleport_control) || index("t", u.usym))
#define	RIN_TELEPORT_CONTROL	270
#define	Polymorph	u.uprops[19].p_flgs
#define	RIN_POLYMORPH	271
#define	Polymorph_control	u.uprops[20].p_flgs
#define	RIN_POLYMORPH_CONTROL	272
#define	DILITHIUM_CRYSTAL	275
#define	DIAMOND	276
#define	RUBY	277
#define	SAPPHIRE	278
#define	EMERALD	279
#define	TURQUOISE	280
#define	AQUAMARINE	281
#define	TOURMALINE	282
#define	TOPAZ	283
#define	OPAL	284
#define	GARNET	285
#define	AMETHYST	286
#define	AGATE	287
#define	ONYX	288
#define	JASPER	289
#define	JADE	290
/* #define	WORTHLESS_PIECE_OF_BLUE_GLASS	291 */
/* #define	WORTHLESS_PIECE_OF_RED_GLASS	292 */
/* #define	WORTHLESS_PIECE_OF_YELLOW_GLASS	293 */
/* #define	WORTHLESS_PIECE_OF_GREEN_GLASS	294 */

#define	CORPSE		DEAD_HUMAN
#define	DEAD_KOP		DEAD_KOBOLD
#define	DEAD_GIANT_SPIDER	DEAD_GIANT_SCORPION
#define	DEAD_ROCKMOLE		DEAD_GIANT_RAT
#define	LAST_GEM	(JADE+1)
#define	LAST_RING	21
#define MAXSPELL	35
#define	NROFOBJECTS	294
