/* A lexical scanner for NetHack generated by flex */

/* Scanner skeleton version:
 * flexhack.skl 3.3.0 (from .../flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47)
 */
#define FLEXHACK_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include "config.h"
#define yyconst const	/* some code inserted by flex will refer to yyconst */

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* Return all but the first 'n' matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */

int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void FDECL(yyrestart, (FILE *));

void FDECL(yy_switch_to_buffer, (YY_BUFFER_STATE));
void NDECL(yy_load_buffer_state);
YY_BUFFER_STATE FDECL(yy_create_buffer, (FILE *,int));
void FDECL(yy_delete_buffer, (YY_BUFFER_STATE));
void FDECL(yy_init_buffer, (YY_BUFFER_STATE,FILE *));
void FDECL(yy_flush_buffer, (YY_BUFFER_STATE));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

static genericptr_t FDECL(yy_flex_alloc, (yy_size_t));
static genericptr_t FDECL(yy_flex_realloc2, (genericptr_t,yy_size_t,int));
static void FDECL(yy_flex_free, (genericptr_t));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type NDECL(yy_get_previous_state);
static yy_state_type FDECL(yy_try_NUL_trans, (yy_state_type));
static int NDECL(yy_get_next_buffer);
static void FDECL(yy_fatal_error, (const char *));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 109
#define YY_END_OF_BUFFER 110
static yyconst short int yy_accept[611] =
    {   0,
        0,    0,    0,    0,  110,  108,  106,  105,  108,  108,
      108,  103,    4,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
        2,  106,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  106,    0,  104,    0,
      103,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   85,    0,    0,    3,    0,
        2,  106,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    2,    0,  107,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   72,    0,    0,   67,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   65,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   17,    0,    0,    0,
        0,    0,   40,    0,    0,    0,    6,    0,    0,   42,
        0,    0,    0,   33,    0,    0,    0,   36,   32,    0,
        0,    0,   16,    0,    0,  102,    0,    0,    0,    0,

        0,    0,    0,    0,   91,    0,    0,    0,    0,    0,
       86,   89,   51,    0,    0,    0,    0,    0,    0,   60,
        0,    0,    0,    0,    0,   92,    0,    0,    0,    0,
        0,   55,    0,    0,    0,   45,    0,    0,    0,    0,
        0,    0,    0,    0,   88,    0,    0,    0,   53,   12,
        0,    0,    0,    0,   25,    0,    0,    0,    0,    0,
        0,   10,    0,    0,    0,    0,    8,    0,    0,    0,
        7,    0,    0,    0,    0,    0,    0,   27,    0,    0,
        0,   59,   84,    0,    0,   78,    0,    0,    0,    0,
       74,    0,    0,    0,    0,   87,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       50,    0,    0,    0,   58,    0,   64,    0,    0,    0,
       52,    0,    0,   68,    0,    0,   30,   43,    0,    0,
        0,    0,    0,    0,    0,   26,    0,    0,    0,    0,
        0,   13,   28,    0,   21,    0,    0,    0,    0,   77,
        0,   66,   49,   62,   46,    0,   95,    0,   69,    0,
        0,    0,    0,    0,   47,    0,    0,    0,    0,    0,
        0,   48,   99,    0,   56,    0,   54,    0,    0,   83,
        0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    5,   15,    0,    0,    0,   37,    0,   20,

        0,   93,    0,   90,    0,    0,    0,   76,    0,    0,
        0,    0,   57,   73,   71,    0,    0,   82,    0,    0,
        0,    0,   39,    0,    0,   31,   11,    9,   19,    0,
        0,    0,    0,    0,    0,    0,  100,    0,    0,    0,
        0,    0,    0,    0,   81,    0,   75,    0,   94,   70,
       14,    0,   41,    0,    0,    0,    0,    0,    0,    0,
       96,   61,    0,   98,   44,   79,   80,    0,    0,   18,
        0,    0,    0,    0,    0,    0,    0,   63,   97,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   34,   35,
        0,    0,    0,    0,    0,  101,    0,    0,    0,   24,

        0,    0,    0,   22,    0,    0,   23,   29,   38,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    1,    8,    1,
        1,    1,    9,    1,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    1,    1,
        1,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
        1,   30,   31,   32,   33,   34,   35,    1,   36,   37,
       38,   11,   39,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,    1,   57,   58,   59,   60,   61,   62,    1,
        1,    1,   11,   11,   11,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    2,    3,    2,    1,    2,    1,    1,    2,    2,
        2,    1,    1,    2,    2,    2,    1,    1,    2,    1,
        2,    2,    1,    2,    2,    1,    1,    1,    2,    1,
        2,    2,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[615] =
    {   0,
        0,   57,   81,   60,  740,  741,   63,  741,  734,    0,
      726,  725,  741,  711,  705,   43,   40,  707,   44,   60,
      706,   59,   61,   66,  717,  703,   90,   87,   63,  716,
       70,   65,   69,   80,   76,   57,   66,   89,   92,   98,
       97,   92,   98,  105,  108,  100,  104,  684,  725,  147,
      741,  164,  167,  169,  171,  174,  177,  700,  157,  162,
      173,  165,  178,  189,  170,  217,  160,  721,  741,  717,
      712,  691,  708,  707,  165,  692,  705,  698,  703,  683,
      687,  689,  691,  695,  677,  673,  678,  681,  681,  182,
      683,  184,  678,  684,  675,  675,  687,  685,  674,  684,

      672,  147,  190,  166,  654,  643,  653,  648,  633,  636,
      633,  635,  647,  632,  632,  628,  622,  625,  624,  634,
      628,  627,  161,  620,  615,  176,  617,  632,  198,  617,
      619,  612,  206,  621,  625,  628,  627,  613,  619,  611,
      188,  604,  607,  602,  212,  741,  603,  657,  741,  187,
      741,  264,  227,  254,  255,  254,  258,  261,  263,  266,
      269,  741,    0,  741,  645,  631,  630,  624,  625,  624,
      618,  622,  631,  623,  623,  631,  615,  629,  627,  626,
      612,  611,  623,  626,  599,  620,  612,  604,  618,  612,
      607,  608,  609,  600,  611,  599,  602,  231,  579,  584,

      569,  578,  571,  563,  561,  568,  564,  558,  561,  557,
      555,  555,  558,  552,  551,  552,  550,  555,  560,  561,
      545,  741,  544,  545,  741,  550,  555,  544,  556,  546,
      538,  536,  542,  538,  539,  546,  531,  544,  543,  533,
      543,  542,  540,  535,  539,  524,  531,  520,  741,  533,
      517,  527,  526,  515,  570,  271,  274,  546,  277,  282,
      284,  541,  554,  553,  554,  545,  741,  551,  551,  533,
      531,  544,  741,  521,  542,  534,  523,  543,  524,  741,
      526,  276,  538,  741,  539,  524,  523,  741,  741,  520,
      521,  519,  741,  525,  278,  741,  492,  488,  487,  498,

      497,  483,  485,  494,  741,  493,  479,  491,  494,  489,
      741,  741,  741,  492,  487,  486,  520,  483,  479,  741,
      482,  481,  484,  470,  473,  741,  463,  464,  471,  464,
      477,  741,  469,  464,  472,  741,  469,  468,  457,  452,
      451,  450,  454,  459,  741,  449,  453,  445,  741,  741,
      285,  489,  292,  294,  741,  481,  483,  478,  482,  468,
      463,  741,  482,  463,  468,  463,  741,  478,  471,  472,
      741,  467,  474,  455,  461,  459,  457,  741,  455,  454,
      462,  741,  741,  435,  423,  741,  433,  424,  422,  418,
      741,  430,  424,  428,  410,  741,  426,  261,  417,  416,

      420,  422,  406,  406,  418,  417,  420,  413,  402,  402,
      741,  412,  397,  409,  741,  401,  741,  393,  394,  406,
      741,  392,  397,  741,  419,  305,  741,  741,  420,  418,
      423,  422,  421,  412,  427,  741,  415,  421,  408,  417,
      405,  741,  741,  395,  741,  408,  403,  396,  390,  741,
      386,  741,  741,  741,  741,  375,  741,  383,  741,  382,
      377,  370,  379,  374,  741,  362,  362,  377,  362,  366,
      363,  741,  741,  360,  741,  355,  741,  361,  364,  741,
      367,  366,  741,  293,  392,  379,  391,  380,  379,  369,
      375,  379,  741,  741,  382,  370,  304,  741,  368,  741,

      347,  741,  353,  741,  351,  349,  340,  741,  339,  336,
      347,  332,  741,  741,  741,  335,  337,  741,  341,  343,
      342,  355,  741,  364,  363,  741,  741,  741,  741,  368,
      346,  352,  351,  363,  352,  336,  741,  331,  315,  325,
      315,  317,  325,  312,  741,  311,  741,  319,  741,  741,
      741,  348,  741,  350,  350,  333,  335,  338,  346,  329,
      741,  741,  299,  741,  741,  741,  741,  298,  297,  741,
      330,  329,  323,  321,  333,  334,  331,  741,  741,  303,
      329,  321,  323,  312,  315,  310,  307,  282,  741,  741,
      308,  303,  282,  231,  239,  741,  226,  210,  203,  741,

      189,  115,   83,  741,   74,   45,  741,  741,  741,  741,
      333,  336,  338,  340
    } ;

static yyconst short int yy_def[615] =
    {   0,
      610,    1,    1,    3,  610,  610,  610,  610,  611,  612,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  613,  610,
      610,  614,  614,  614,  614,  614,  614,  610,   57,   57,
       57,   57,   57,   61,   61,  613,  610,  611,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,

      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  613,  610,  610,
      610,  614,  614,  614,   61,  610,   61,   61,   61,   61,
       61,  610,   66,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,

      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,   61,   61,  610,   61,   61,
       61,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,

      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
       61,  610,   61,   61,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,

      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,   61,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,   61,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,

      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,

      610,  610,  610,  610,  610,  610,  610,  610,  610,    0,
      610,  610,  610,  610
    } ;

static yyconst short int yy_nxt[804] =
    {   0,
        6,    7,    8,    7,    9,    6,    6,   10,   11,   11,
        6,   12,   13,   14,   15,   16,   17,   18,   19,   20,
        6,   21,    6,    6,   22,   23,   24,   25,   26,   27,
       28,   29,    6,    6,   30,    6,    6,   31,    6,    6,
       32,   33,   34,   35,   36,   37,    6,   38,    6,    6,
        6,   39,   40,   41,   42,   43,   44,   45,   46,   47,
        6,   48,   49,   74,   67,   66,   67,   76,   79,   77,
       75,   80,   84,  102,   86,  609,   85,   81,   87,   89,
       99,  103,   50,   51,   52,   50,   53,   82,   88,   54,
       54,   53,  100,   90,   55,   56,   57,  119,   58,   59,

      608,   53,   60,   93,   53,   61,  121,   94,   96,   62,
      120,   63,   64,  607,  122,   65,  104,   95,   97,   98,
      108,  105,  106,  109,  112,  110,  107,  113,  111,  123,
      117,  114,  125,  134,  115,  118,  126,  129,  130,  116,
      127,  132,  136,  124,  606,  138,  128,  135,  140,  137,
      102,  133,  131,  139,  143,  141,  144,  145,  103,  146,
      150,   67,  142,   67,   87,   67,  151,  152,  610,  151,
      610,  151,  610,  151,   88,  610,  151,  153,  610,  151,
       71,  157,  153,  161,   80,  153,  158,  610,   83,  610,
       85,  168,   92,  153,  169,  154,  198,  155,  153,  159,

      610,  103,  153,   73,   75,  610,   99,  184,  185,  160,
       98,  187,  219,  188,  199,  255,  605,  220,  100,  162,
      163,  223,  163,  180,  200,  163,  163,  163,  610,  151,
      163,  163,  163,  604,  295,  163,  224,  163,  163,  603,
      163,  163,  246,  227,  247,  163,  233,  163,  163,  234,
      228,  163,  229,  602,  251,  610,  151,  252,  235,  236,
      601,  600,  237,  253,  238,   67,  151,  152,  257,  296,
      258,  259,  610,  172,  153,  610,  153,  178,  610,  260,
      610,  295,  153,  610,  351,  256,  610,  153,  610,  192,
      153,  610,  372,  261,  610,  153,  270,  153,  153,  610,

      264,  610,  610,  353,  373,  153,  153,  153,  354,  610,
      610,  610,  460,  599,  355,  426,  296,  461,  153,  532,
      598,  378,  610,  484,  597,  596,  595,  594,  500,  533,
      593,  534,  535,   68,   68,   68,   70,   70,  148,  148,
      148,  153,  153,  592,  591,  590,  589,  588,  587,  586,
      585,  584,  583,  582,  581,  580,  579,  578,  577,  576,
      575,  574,  573,  572,  571,  570,  569,  568,  567,  566,
      565,  564,  563,  562,  561,  560,  559,  558,  557,  556,
      555,  554,  553,  552,  551,  550,  549,  548,  547,  546,
      545,  544,  543,  542,  541,  540,  539,  538,  537,  536,

      531,  530,  529,  528,  527,  526,  525,  524,  523,  522,
      521,  520,  519,  518,  517,  516,  515,  514,  513,  512,
      511,  510,  509,  508,  507,  506,  505,  504,  503,  502,
      501,  500,  499,  498,  497,  496,  495,  494,  493,  492,
      491,  490,  489,  488,  487,  486,  485,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  464,  463,  462,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,

      428,  427,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  352,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,

      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  149,
      254,  250,  249,  248,  245,  244,  243,  242,  241,  240,
      239,  232,  231,  230,  226,  225,  222,  221,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  197,  196,  195,  194,

      193,  192,  191,  190,  189,  186,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      167,  166,  165,   71,  164,   69,  156,  149,  147,  101,
       92,   91,   83,   78,   73,   72,   71,   71,   69,  610,
        5,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,

      610,  610,  610
    } ;

static yyconst short int yy_chk[804] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,   16,    7,    4,    7,   17,   19,   17,
       16,   19,   22,   31,   23,  606,   22,   20,   23,   24,
       29,   31,    2,    3,    3,    4,    3,   20,   23,    3,
        3,    3,   29,   24,    3,    3,    3,   36,    3,    3,

      605,    3,    3,   27,    3,    3,   37,   27,   28,    3,
       36,    3,    3,  603,   37,    3,   32,   27,   28,   28,
       33,   32,   32,   33,   34,   33,   32,   34,   33,   38,
       35,   34,   39,   42,   34,   35,   39,   40,   40,   34,
       39,   41,   43,   38,  602,   44,   39,   42,   45,   43,
      102,   41,   40,   44,   46,   45,   46,   47,  102,   47,
       50,   67,   45,   67,   50,   52,   52,   52,   53,   53,
       54,   54,   55,   55,   50,   56,   56,   59,   57,   57,
       54,   59,   60,   65,   59,   62,   61,   65,   60,   60,
       61,   75,   62,   61,   75,   55,  103,   57,   63,   63,

       61,  103,   64,   56,   57,   63,   64,   90,   90,   63,
       63,   92,  123,   92,  104,  150,  601,  123,   64,   66,
       66,  126,   66,  150,  104,   66,   66,   66,  153,  153,
       66,   66,   66,  599,  198,   66,  126,   66,   66,  598,
       66,   66,  141,  129,  141,   66,  133,   66,   66,  133,
      129,   66,  129,  597,  145,  154,  154,  145,  133,  133,
      595,  594,  133,  145,  133,  152,  152,  152,  155,  198,
      156,  157,  155,  156,  158,  157,  159,  158,  158,  160,
      159,  295,  161,  160,  256,  154,  161,  257,  256,  159,
      259,  257,  282,  161,  259,  260,  259,  261,  351,  260,

      257,  261,  351,  260,  282,  353,  484,  354,  261,  353,
      484,  354,  398,  593,  351,  354,  295,  398,  426,  497,
      592,  353,  426,  426,  591,  588,  587,  586,  484,  497,
      585,  497,  497,  611,  611,  611,  612,  612,  613,  613,
      613,  614,  614,  584,  583,  582,  581,  580,  577,  576,
      575,  574,  573,  572,  571,  569,  568,  563,  560,  559,
      558,  557,  556,  555,  554,  552,  548,  546,  544,  543,
      542,  541,  540,  539,  538,  536,  535,  534,  533,  532,
      531,  530,  525,  524,  522,  521,  520,  519,  517,  516,
      512,  511,  510,  509,  507,  506,  505,  503,  501,  499,

      496,  495,  492,  491,  490,  489,  488,  487,  486,  485,
      482,  481,  479,  478,  476,  474,  471,  470,  469,  468,
      467,  466,  464,  463,  462,  461,  460,  458,  456,  451,
      449,  448,  447,  446,  444,  441,  440,  439,  438,  437,
      435,  434,  433,  432,  431,  430,  429,  425,  423,  422,
      420,  419,  418,  416,  414,  413,  412,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  397,
      395,  394,  393,  392,  390,  389,  388,  387,  385,  384,
      381,  380,  379,  377,  376,  375,  374,  373,  372,  370,
      369,  368,  366,  365,  364,  363,  361,  360,  359,  358,

      357,  356,  352,  348,  347,  346,  344,  343,  342,  341,
      340,  339,  338,  337,  335,  334,  333,  331,  330,  329,
      328,  327,  325,  324,  323,  322,  321,  319,  318,  317,
      316,  315,  314,  310,  309,  308,  307,  306,  304,  303,
      302,  301,  300,  299,  298,  297,  294,  292,  291,  290,
      287,  286,  285,  283,  281,  279,  278,  277,  276,  275,
      274,  272,  271,  270,  269,  268,  266,  265,  264,  263,
      262,  258,  255,  254,  253,  252,  251,  250,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,

      226,  224,  223,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  148,
      147,  144,  143,  142,  140,  139,  138,  137,  136,  135,
      134,  132,  131,  130,  128,  127,  125,  124,  122,  121,
      120,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  101,  100,   99,   98,

       97,   96,   95,   94,   93,   91,   89,   88,   87,   86,
       85,   84,   83,   82,   81,   80,   79,   78,   77,   76,
       74,   73,   72,   71,   70,   68,   58,   49,   48,   30,
       26,   25,   21,   18,   15,   14,   12,   11,    9,    5,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,
      610,  610,  610,  610,  610,  610,  610,  610,  610,  610,

      610,  610,  610
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#define INITIAL 0
/*	SCCS Id: @(#)lev_lex.c	3.3	96/05/16	*/
/*	Copyright (c) 1989 by Jean-Christophe Collet */
/* NetHack may be freely redistributed.  See license for details. */

#define LEV_LEX_C

#include "hack.h"
#include "lev_comp.h"
#include "sp_lev.h"

/* Most of these don't exist in flex, yywrap is macro and
 * yyunput is properly declared in flex.skel.
 */
#if !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
int FDECL(yyback, (int *,int));
int NDECL(yylook);
int NDECL(yyinput);
int NDECL(yywrap);
int NDECL(yylex);
	/* Traditional lexes let yyunput() and yyoutput() default to int;
	 * newer ones may declare them as void since they don't return
	 * values.  For even more fun, the lex supplied as part of the
	 * newer unbundled compiler for SunOS 4.x adds the void declarations
	 * (under __STDC__ or _cplusplus ifdefs -- otherwise they remain
	 * int) while the bundled lex and the one with the older unbundled
	 * compiler do not.  To detect this, we need help from outside --
	 * sys/unix/Makefile.utl.
	 */
# if defined(NeXT) || defined(SVR4) || defined(_AIX32)
#  define VOIDYYPUT
# endif
# if !defined(VOIDYYPUT)
#  if defined(POSIX_TYPES) && !defined(BOS) && !defined(HISX) && !defined(_M_UNIX) && !defined(VMS)
#   define VOIDYYPUT
#  endif
# endif
# if !defined(VOIDYYPUT) && defined(WEIRD_LEX)
#  if defined(SUNOS4) && defined(__STDC__) && (WEIRD_LEX > 1)
#   define VOIDYYPUT
#  endif
# endif
# ifdef VOIDYYPUT
void FDECL(yyunput, (int));
void FDECL(yyoutput, (int));
# else
int FDECL(yyunput, (int));
int FDECL(yyoutput, (int));
# endif
#endif	/* !FLEX_SCANNER && !FLEXHACK_SCANNER */

#ifdef FLEX_SCANNER
#define YY_MALLOC_DECL \
	      genericptr_t FDECL(malloc, (size_t)); \
	      genericptr_t FDECL(realloc, (genericptr_t,size_t));
#endif

void FDECL(init_yyin, (FILE *));
void FDECL(init_yyout, (FILE *));

/*
 * This doesn't always get put in lev_comp.h
 * (esp. when using older versions of bison).
 */
extern YYSTYPE yylval;

int line_number = 1, colon_line_number = 1;
static char map[4096];
static int map_cnt = 0;

/*
 *	This is a hack required by Michael Hamel to get things
 *	working on the Mac.
 */
#if defined(applec) && !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
#undef input
#undef unput
#define unput(c) { yytchar = (c); if (yytchar == 10) yylineno--; *yysptr++ = yytchar; }
# ifndef YYNEWLINE
# define YYNEWLINE 10
# endif

char
input()		/* Under MPW \n is chr(13)! Compensate for this. */
{
	if (yysptr > yysbuf) return(*--yysptr);
	else {
		yytchar = getc(yyin);
		if (yytchar == '\n') {
		    yylineno++;
		    return(YYNEWLINE);
		}
		if (yytchar == EOF) return(0);
		else		    return(yytchar);
	}
}
#endif	/* applec && !FLEX_SCANNER && !FLEXHACK_SCANNER */

#define MAPC 1


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
extern int NDECL(yywrap);
#endif

#ifndef YY_NO_UNPUT
static void FDECL(yyunput, (int,char *));
#endif

#ifndef yytext_ptr
static void FDECL(yy_flex_strncpy, (char *,const char *,int));
#endif

#ifndef YY_NO_INPUT
static int NDECL(input);
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

int NDECL(yylex);
int yylex()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 611 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 741 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
		  BEGIN(INITIAL);
		  yylval.map = (char *) alloc(map_cnt + 1);
		  (void) strncpy(yylval.map, map, map_cnt);
		  yylval.map[map_cnt] = 0;
		  map_cnt = 0;
		  return MAP_ID;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
		  line_number++;
		  (void) strncpy(map + map_cnt, yytext, yyleng);
		  map_cnt += yyleng;
		  map[map_cnt] = 0;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
{ line_number++; }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ colon_line_number = line_number; return ':'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
return MESSAGE_ID;
	YY_BREAK
case 6:
YY_RULE_SETUP
return MAZE_ID;
	YY_BREAK
case 7:
YY_RULE_SETUP
return NOMAP_ID;
	YY_BREAK
case 8:
YY_RULE_SETUP
return LEVEL_ID;
	YY_BREAK
case 9:
YY_RULE_SETUP
return LEV_INIT_ID;
	YY_BREAK
case 10:
YY_RULE_SETUP
return FLAGS_ID;
	YY_BREAK
case 11:
YY_RULE_SETUP
return GEOMETRY_ID;
	YY_BREAK
case 12:
YY_RULE_SETUP
{ BEGIN(MAPC); line_number++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
return OBJECT_ID;
	YY_BREAK
case 14:
YY_RULE_SETUP
return COBJECT_ID;
	YY_BREAK
case 15:
YY_RULE_SETUP
return MONSTER_ID;
	YY_BREAK
case 16:
YY_RULE_SETUP
return TRAP_ID;
	YY_BREAK
case 17:
YY_RULE_SETUP
return DOOR_ID;
	YY_BREAK
case 18:
YY_RULE_SETUP
return DRAWBRIDGE_ID;
	YY_BREAK
case 19:
YY_RULE_SETUP
return MAZEWALK_ID;
	YY_BREAK
case 20:
YY_RULE_SETUP
return WALLIFY_ID;
	YY_BREAK
case 21:
YY_RULE_SETUP
return REGION_ID;
	YY_BREAK
case 22:
YY_RULE_SETUP
return RANDOM_OBJECTS_ID;
	YY_BREAK
case 23:
YY_RULE_SETUP
return RANDOM_MONSTERS_ID;
	YY_BREAK
case 24:
YY_RULE_SETUP
return RANDOM_PLACES_ID;
	YY_BREAK
case 25:
YY_RULE_SETUP
return ALTAR_ID;
	YY_BREAK
case 26:
YY_RULE_SETUP
return LADDER_ID;
	YY_BREAK
case 27:
YY_RULE_SETUP
return STAIR_ID;
	YY_BREAK
case 28:
YY_RULE_SETUP
return PORTAL_ID;
	YY_BREAK
case 29:
YY_RULE_SETUP
return TELEPRT_ID;
	YY_BREAK
case 30:
YY_RULE_SETUP
return BRANCH_ID;
	YY_BREAK
case 31:
YY_RULE_SETUP
return FOUNTAIN_ID;
	YY_BREAK
case 32:
YY_RULE_SETUP
return SINK_ID;
	YY_BREAK
case 33:
YY_RULE_SETUP
return POOL_ID;
	YY_BREAK
case 34:
YY_RULE_SETUP
return NON_DIGGABLE_ID;
	YY_BREAK
case 35:
YY_RULE_SETUP
return NON_PASSWALL_ID;
	YY_BREAK
case 36:
YY_RULE_SETUP
return ROOM_ID;
	YY_BREAK
case 37:
YY_RULE_SETUP
return SUBROOM_ID;
	YY_BREAK
case 38:
YY_RULE_SETUP
return RAND_CORRIDOR_ID;
	YY_BREAK
case 39:
YY_RULE_SETUP
return CORRIDOR_ID;
	YY_BREAK
case 40:
YY_RULE_SETUP
return GOLD_ID;
	YY_BREAK
case 41:
YY_RULE_SETUP
return ENGRAVING_ID;
	YY_BREAK
case 42:
YY_RULE_SETUP
return NAME_ID;
	YY_BREAK
case 43:
YY_RULE_SETUP
return CHANCE_ID;
	YY_BREAK
case 44:
YY_RULE_SETUP
return LEV;
	YY_BREAK
case 45:
YY_RULE_SETUP
{ yylval.i=D_ISOPEN; return DOOR_STATE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
{ yylval.i=D_CLOSED; return DOOR_STATE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
{ yylval.i=D_LOCKED; return DOOR_STATE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ yylval.i=D_NODOOR; return DOOR_STATE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
{ yylval.i=D_BROKEN; return DOOR_STATE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
{ yylval.i=W_NORTH; return DIRECTION; }
	YY_BREAK
case 51:
YY_RULE_SETUP
{ yylval.i=W_EAST; return DIRECTION; }
	YY_BREAK
case 52:
YY_RULE_SETUP
{ yylval.i=W_SOUTH; return DIRECTION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ yylval.i=W_WEST; return DIRECTION; }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ yylval.i = -1; return RANDOM_TYPE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
{ yylval.i = -2; return NONE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
return O_REGISTER;
	YY_BREAK
case 57:
YY_RULE_SETUP
return M_REGISTER;
	YY_BREAK
case 58:
YY_RULE_SETUP
return P_REGISTER;
	YY_BREAK
case 59:
YY_RULE_SETUP
return A_REGISTER;
	YY_BREAK
case 60:
YY_RULE_SETUP
{ yylval.i=1; return LEFT_OR_RIGHT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
{ yylval.i=2; return LEFT_OR_RIGHT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
{ yylval.i=3; return CENTER; }
	YY_BREAK
case 63:
YY_RULE_SETUP
{ yylval.i=4; return LEFT_OR_RIGHT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ yylval.i=5; return LEFT_OR_RIGHT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ yylval.i=1; return TOP_OR_BOT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ yylval.i=5; return TOP_OR_BOT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ yylval.i=1; return LIGHT_STATE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
{ yylval.i=0; return LIGHT_STATE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
{ yylval.i=0; return FILLING; }
	YY_BREAK
case 70:
YY_RULE_SETUP
{ yylval.i=1; return FILLING; }
	YY_BREAK
case 71:
YY_RULE_SETUP
{ yylval.i= AM_NONE; return ALIGNMENT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
{ yylval.i= AM_LAWFUL; return ALIGNMENT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
{ yylval.i= AM_NEUTRAL; return ALIGNMENT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ yylval.i= AM_CHAOTIC; return ALIGNMENT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
{ yylval.i=1; return MON_ATTITUDE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
{ yylval.i=0; return MON_ATTITUDE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
{ yylval.i=1; return MON_ALERTNESS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
{ yylval.i=0; return MON_ALERTNESS; }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ yylval.i= M_AP_FURNITURE; return MON_APPEARANCE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
{ yylval.i= M_AP_MONSTER;   return MON_APPEARANCE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
{ yylval.i= M_AP_OBJECT;    return MON_APPEARANCE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ yylval.i=2; return ALTAR_TYPE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ yylval.i=1; return ALTAR_TYPE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
{ yylval.i=0; return ALTAR_TYPE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
{ yylval.i=1; return UP_OR_DOWN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
{ yylval.i=0; return UP_OR_DOWN; }
	YY_BREAK
case 87:
YY_RULE_SETUP
{ yylval.i=0; return BOOLEAN; }
	YY_BREAK
case 88:
YY_RULE_SETUP
{ yylval.i=1; return BOOLEAN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ yylval.i=DUST; return ENGRAVING_TYPE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
{ yylval.i=ENGRAVE; return ENGRAVING_TYPE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
{ yylval.i=BURN; return ENGRAVING_TYPE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
{ yylval.i=MARK; return ENGRAVING_TYPE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
{ yylval.i=1; return CURSE_TYPE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
{ yylval.i=2; return CURSE_TYPE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
{ yylval.i=3; return CURSE_TYPE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
{ return CONTAINED; }
	YY_BREAK
case 97:
YY_RULE_SETUP
{ yylval.i=NOTELEPORT; return FLAG_TYPE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
{ yylval.i=HARDFLOOR; return FLAG_TYPE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
{ yylval.i=NOMMAP; return FLAG_TYPE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
{ yylval.i=ARBOREAL; return FLAG_TYPE; }	/* KMH */
	YY_BREAK
case 101:
YY_RULE_SETUP
{ yylval.i=SHORTSIGHTED; return FLAG_TYPE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
{ yylval.i = atoi(yytext + 1); return PERCENT; }
	YY_BREAK
case 103:
YY_RULE_SETUP
{ yylval.i=atoi(yytext); return INTEGER; }
	YY_BREAK
case 104:
YY_RULE_SETUP
{ yytext[yyleng-1] = 0; /* Discard the trailing \" */
		  yylval.map = (char *) alloc(strlen(yytext+1)+1);
		  Strcpy(yylval.map, yytext+1); /* Discard the first \" */
		  return STRING; }
	YY_BREAK
case 105:
YY_RULE_SETUP
{ line_number++; }
	YY_BREAK
case 106:
YY_RULE_SETUP
;
	YY_BREAK
case 107:
YY_RULE_SETUP
{ yylval.i = yytext[1]; return CHAR; }
	YY_BREAK
case 108:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 109:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MAPC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int old_size = b->yy_buf_size + 2;
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc2( (genericptr_t) b->yy_ch_buf,
							 b->yy_buf_size + 2, old_size );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 611 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 611 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 610);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


static int input()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					return input();
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


void yyrestart( input_file )
FILE *input_file;
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yy_delete_buffer( b )
YY_BUFFER_STATE b;
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (genericptr_t) b->yy_ch_buf );

	yy_flex_free( (genericptr_t) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int FDECL(isatty, (int));
#endif
#endif

void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#ifdef YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#ifdef YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


void yy_flush_buffer( b )
YY_BUFFER_STATE b;
	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}



#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error( msg )
const char msg[];
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
static void yy_flex_strncpy( s1, s2, n )
char *s1;
const char *s2;
int n;
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


static genericptr_t yy_flex_alloc( size )
yy_size_t size;
	{
	return (genericptr_t) alloc((unsigned)size);
	}

/* we want to avoid use of realloc(), so we require that caller supply the
   size of the old block of memory */
static genericptr_t yy_flex_realloc2( ptr, size, old_size )
genericptr_t ptr;
yy_size_t size;
int old_size;
	{
	genericptr_t outptr = yy_flex_alloc(size);

	if (ptr) {
	    char *p = (char *) outptr, *q = (char *) ptr;

	    while (--old_size >= 0) *p++ = *q++;
	    yy_flex_free(ptr);
	}
	return outptr;
	}

static void yy_flex_free( ptr )
genericptr_t ptr;
	{
	free( ptr );
	}

/*flexhack.skl*/

#ifdef	AMIGA
long *alloc(n)
	unsigned n;
{
	return ((long *)malloc (n));
}
#endif

/* routine to switch to another input file; needed for flex */
void init_yyin( input_f )
FILE *input_f;
{
#if defined(FLEX_SCANNER) || defined(FLEXHACK_SCANNER)
	if (yyin)
	    yyrestart(input_f);
	else
#endif
	    yyin = input_f;
}
/* analogous routine (for completeness) */
void init_yyout( output_f )
FILE *output_f;
{
	yyout = output_f;
}

/*lev_comp.l*/
