/*	SCCS Id: @(#)version.c	3.1	92/01/04	*/
/* Copyright (c) Stichting Mathematisch Centrum, Amsterdam, 1985. */
/* NetHack may be freely redistributed.  See license for details. */

#include	"hack.h"
#include	"date.h"
#ifndef BETA
# if defined(MICRO) && !defined(AMIGA) && !defined(TOS) && !defined(OS2_HPFS)
# include	"patchlev.h"
# else
# include	"patchlevel.h"
# endif
#endif

int
doversion()
{
#ifdef BETA
	pline("%s NetHack Beta Version %s - last build %s.",
#else
	pline("%s NetHack Version %s.%d - last build %s.",
#endif
		PORT_ID, VERSION,
#ifndef BETA
		PATCHLEVEL,
#endif
		BUILD_DATE);	/* from date.h, generated by 'makedefs' */
	return 0;
}

int
doextversion()
{
	display_file(OPTIONS_USED, TRUE);
	return 0;
}

#ifdef MICRO
boolean
comp_times(filetime)
long filetime;
{
	return (filetime < BUILD_TIME);
}
#endif

/*version.c*/
